// ═══════════════════════════════════════════════════════════
// S&P 500 DATA — Top 50 Constituent Companies
// ═══════════════════════════════════════════════════════════

export const sp500Companies = [
  { ticker: 'AAPL',  name: 'Apple Inc.',                    sector: 'Technology',    subIndustry: 'Technology Hardware, Storage & Peripherals',  hq: 'Cupertino, CA' },
  { ticker: 'MSFT',  name: 'Microsoft Corporation',         sector: 'Technology',    subIndustry: 'Systems Software',                           hq: 'Redmond, WA' },
  { ticker: 'AMZN',  name: 'Amazon.com Inc.',               sector: 'Consumer',      subIndustry: 'Broadline Retail',                           hq: 'Seattle, WA' },
  { ticker: 'NVDA',  name: 'NVIDIA Corporation',            sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'Santa Clara, CA' },
  { ticker: 'GOOGL', name: 'Alphabet Inc.',                 sector: 'Technology',    subIndustry: 'Interactive Media & Services',                hq: 'Mountain View, CA' },
  { ticker: 'META',  name: 'Meta Platforms Inc.',            sector: 'Technology',    subIndustry: 'Interactive Media & Services',                hq: 'Menlo Park, CA' },
  { ticker: 'TSLA',  name: 'Tesla Inc.',                    sector: 'Consumer',      subIndustry: 'Automobile Manufacturers',                   hq: 'Austin, TX' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc.',       sector: 'Finance',       subIndustry: 'Multi-Sector Holdings',                      hq: 'Omaha, NE' },
  { ticker: 'UNH',   name: 'UnitedHealth Group Inc.',       sector: 'Healthcare',    subIndustry: 'Managed Health Care',                        hq: 'Minnetonka, MN' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',             sector: 'Healthcare',    subIndustry: 'Pharmaceuticals',                            hq: 'New Brunswick, NJ' },
  { ticker: 'V',     name: 'Visa Inc.',                     sector: 'Finance',       subIndustry: 'Transaction & Payment Processing Services',  hq: 'San Francisco, CA' },
  { ticker: 'JPM',   name: 'JPMorgan Chase & Co.',          sector: 'Finance',       subIndustry: 'Diversified Banks',                          hq: 'New York, NY' },
  { ticker: 'XOM',   name: 'Exxon Mobil Corporation',       sector: 'Energy',        subIndustry: 'Integrated Oil & Gas',                       hq: 'Spring, TX' },
  { ticker: 'PG',    name: 'Procter & Gamble Co.',          sector: 'Consumer',      subIndustry: 'Household Products',                         hq: 'Cincinnati, OH' },
  { ticker: 'MA',    name: 'Mastercard Inc.',               sector: 'Finance',       subIndustry: 'Transaction & Payment Processing Services',  hq: 'Purchase, NY' },
  { ticker: 'HD',    name: 'The Home Depot Inc.',           sector: 'Consumer',      subIndustry: 'Home Improvement Retail',                    hq: 'Atlanta, GA' },
  { ticker: 'CVX',   name: 'Chevron Corporation',           sector: 'Energy',        subIndustry: 'Integrated Oil & Gas',                       hq: 'San Ramon, CA' },
  { ticker: 'MRK',   name: 'Merck & Co. Inc.',              sector: 'Healthcare',    subIndustry: 'Pharmaceuticals',                            hq: 'Rahway, NJ' },
  { ticker: 'ABBV',  name: 'AbbVie Inc.',                   sector: 'Healthcare',    subIndustry: 'Biotechnology',                              hq: 'North Chicago, IL' },
  { ticker: 'LLY',   name: 'Eli Lilly and Company',         sector: 'Healthcare',    subIndustry: 'Pharmaceuticals',                            hq: 'Indianapolis, IN' },
  { ticker: 'PEP',   name: 'PepsiCo Inc.',                  sector: 'Consumer',      subIndustry: 'Soft Drinks & Non-alcoholic Beverages',      hq: 'Purchase, NY' },
  { ticker: 'KO',    name: 'The Coca-Cola Company',         sector: 'Consumer',      subIndustry: 'Soft Drinks & Non-alcoholic Beverages',      hq: 'Atlanta, GA' },
  { ticker: 'COST',  name: 'Costco Wholesale Corp.',        sector: 'Consumer',      subIndustry: 'Consumer Staples Merchandise Retail',        hq: 'Issaquah, WA' },
  { ticker: 'AVGO',  name: 'Broadcom Inc.',                 sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'Palo Alto, CA' },
  { ticker: 'WMT',   name: 'Walmart Inc.',                  sector: 'Consumer',      subIndustry: 'Consumer Staples Merchandise Retail',        hq: 'Bentonville, AR' },
  { ticker: 'MCD',   name: "McDonald's Corporation",        sector: 'Consumer',      subIndustry: 'Restaurants',                                hq: 'Chicago, IL' },
  { ticker: 'CSCO',  name: 'Cisco Systems Inc.',            sector: 'Technology',    subIndustry: 'Communications Equipment',                   hq: 'San Jose, CA' },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific Inc.', sector: 'Healthcare',    subIndustry: 'Life Sciences Tools & Services',             hq: 'Waltham, MA' },
  { ticker: 'ACN',   name: 'Accenture plc',                 sector: 'Technology',    subIndustry: 'IT Consulting & Other Services',             hq: 'Dublin, Ireland' },
  { ticker: 'ABT',   name: 'Abbott Laboratories',           sector: 'Healthcare',    subIndustry: 'Health Care Equipment',                      hq: 'Abbott Park, IL' },
  { ticker: 'CRM',   name: 'Salesforce Inc.',               sector: 'Technology',    subIndustry: 'Application Software',                       hq: 'San Francisco, CA' },
  { ticker: 'DHR',   name: 'Danaher Corporation',           sector: 'Healthcare',    subIndustry: 'Health Care Equipment',                      hq: 'Washington, D.C.' },
  { ticker: 'NFLX',  name: 'Netflix Inc.',                  sector: 'Technology',    subIndustry: 'Movies & Entertainment',                     hq: 'Los Gatos, CA' },
  { ticker: 'AMD',   name: 'Advanced Micro Devices Inc.',   sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'Santa Clara, CA' },
  { ticker: 'INTC',  name: 'Intel Corporation',             sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'Santa Clara, CA' },
  { ticker: 'QCOM',  name: 'Qualcomm Inc.',                 sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'San Diego, CA' },
  { ticker: 'TXN',   name: 'Texas Instruments Inc.',        sector: 'Technology',    subIndustry: 'Analog Semiconductors',                      hq: 'Dallas, TX' },
  { ticker: 'NEE',   name: 'NextEra Energy Inc.',           sector: 'Energy',        subIndustry: 'Electric Utilities',                         hq: 'Juno Beach, FL' },
  { ticker: 'UNP',   name: 'Union Pacific Corporation',     sector: 'Industrial',    subIndustry: 'Railroads',                                  hq: 'Omaha, NE' },
  { ticker: 'LOW',   name: "Lowe's Companies Inc.",         sector: 'Consumer',      subIndustry: 'Home Improvement Retail',                    hq: 'Mooresville, NC' },
  { ticker: 'BA',    name: 'The Boeing Company',            sector: 'Industrial',    subIndustry: 'Aerospace & Defense',                        hq: 'Arlington, VA' },
  { ticker: 'GS',    name: 'The Goldman Sachs Group Inc.',  sector: 'Finance',       subIndustry: 'Investment Banking & Brokerage',             hq: 'New York, NY' },
  { ticker: 'MS',    name: 'Morgan Stanley',                sector: 'Finance',       subIndustry: 'Investment Banking & Brokerage',             hq: 'New York, NY' },
  { ticker: 'AXP',   name: 'American Express Company',      sector: 'Finance',       subIndustry: 'Consumer Finance',                           hq: 'New York, NY' },
  { ticker: 'BLK',   name: 'BlackRock Inc.',                sector: 'Finance',       subIndustry: 'Asset Management & Custody Banks',           hq: 'New York, NY' },
  { ticker: 'CAT',   name: 'Caterpillar Inc.',              sector: 'Industrial',    subIndustry: 'Construction Machinery & Heavy Equipment',   hq: 'Irving, TX' },
  { ticker: 'DE',    name: 'Deere & Company',               sector: 'Industrial',    subIndustry: 'Agricultural & Farm Machinery',              hq: 'Moline, IL' },
  { ticker: 'GE',    name: 'GE Aerospace',                  sector: 'Industrial',    subIndustry: 'Aerospace & Defense',                        hq: 'Evendale, OH' },
  { ticker: 'RTX',   name: 'RTX Corporation',               sector: 'Industrial',    subIndustry: 'Aerospace & Defense',                        hq: 'Arlington, VA' },
  { ticker: 'LMT',   name: 'Lockheed Martin Corporation',   sector: 'Industrial',    subIndustry: 'Aerospace & Defense',                        hq: 'Bethesda, MD' },
];

// Sector groupings for filter UI
export const sectorGroups = {
  'All':        null,
  'Tech':       'Technology',
  'Finance':    'Finance',
  'Healthcare': 'Healthcare',
  'Energy':     'Energy',
  'Consumer':   'Consumer',
  'Industrial': 'Industrial',
};
