// ═══════════════════════════════════════════════════════════
// S&P 500 DATA — Top 50 Constituent Companies
// ═══════════════════════════════════════════════════════════

export const sp500Companies = [
  { ticker: 'AAPL',  name: 'Apple Inc.',                    sector: 'Technology',    subIndustry: 'Technology Hardware, Storage & Peripherals',  hq: 'Cupertino, CA' },
  { ticker: 'MSFT',  name: 'Microsoft Corporation',         sector: 'Technology',    subIndustry: 'Systems Software',                           hq: 'Redmond, WA' },
  { ticker: 'AMZN',  name: 'Amazon.com Inc.',               sector: 'Consumer',      subIndustry: 'Broadline Retail',                           hq: 'Seattle, WA' },
  { ticker: 'NVDA',  name: 'NVIDIA Corporation',            sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'Santa Clara, CA' },
  { ticker: 'GOOGL', name: 'Alphabet Inc.',                 sector: 'Technology',    subIndustry: 'Interactive Media & Services',                hq: 'Mountain View, CA' },
  { ticker: 'META',  name: 'Meta Platforms Inc.',            sector: 'Technology',    subIndustry: 'Interactive Media & Services',                hq: 'Menlo Park, CA' },
  { ticker: 'TSLA',  name: 'Tesla Inc.',                    sector: 'Consumer',      subIndustry: 'Automobile Manufacturers',                   hq: 'Austin, TX' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc.',       sector: 'Finance',       subIndustry: 'Multi-Sector Holdings',                      hq: 'Omaha, NE' },
  { ticker: 'UNH',   name: 'UnitedHealth Group Inc.',       sector: 'Healthcare',    subIndustry: 'Managed Health Care',                        hq: 'Minnetonka, MN' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',             sector: 'Healthcare',    subIndustry: 'Pharmaceuticals',                            hq: 'New Brunswick, NJ' },
  { ticker: 'V',     name: 'Visa Inc.',                     sector: 'Finance',       subIndustry: 'Transaction & Payment Processing Services',  hq: 'San Francisco, CA' },
  { ticker: 'JPM',   name: 'JPMorgan Chase & Co.',          sector: 'Finance',       subIndustry: 'Diversified Banks',                          hq: 'New York, NY' },
  { ticker: 'XOM',   name: 'Exxon Mobil Corporation',       sector: 'Energy',        subIndustry: 'Integrated Oil & Gas',                       hq: 'Spring, TX' },
  { ticker: 'PG',    name: 'Procter & Gamble Co.',          sector: 'Consumer',      subIndustry: 'Household Products',                         hq: 'Cincinnati, OH' },
  { ticker: 'MA',    name: 'Mastercard Inc.',               sector: 'Finance',       subIndustry: 'Transaction & Payment Processing Services',  hq: 'Purchase, NY' },
  { ticker: 'HD',    name: 'The Home Depot Inc.',           sector: 'Consumer',      subIndustry: 'Home Improvement Retail',                    hq: 'Atlanta, GA' },
  { ticker: 'CVX',   name: 'Chevron Corporation',           sector: 'Energy',        subIndustry: 'Integrated Oil & Gas',                       hq: 'San Ramon, CA' },
  { ticker: 'MRK',   name: 'Merck & Co. Inc.',              sector: 'Healthcare',    subIndustry: 'Pharmaceuticals',                            hq: 'Rahway, NJ' },
  { ticker: 'ABBV',  name: 'AbbVie Inc.',                   sector: 'Healthcare',    subIndustry: 'Biotechnology',                              hq: 'North Chicago, IL' },
  { ticker: 'LLY',   name: 'Eli Lilly and Company',         sector: 'Healthcare',    subIndustry: 'Pharmaceuticals',                            hq: 'Indianapolis, IN' },
  { ticker: 'PEP',   name: 'PepsiCo Inc.',                  sector: 'Consumer',      subIndustry: 'Soft Drinks & Non-alcoholic Beverages',      hq: 'Purchase, NY' },
  { ticker: 'KO',    name: 'The Coca-Cola Company',         sector: 'Consumer',      subIndustry: 'Soft Drinks & Non-alcoholic Beverages',      hq: 'Atlanta, GA' },
  { ticker: 'COST',  name: 'Costco Wholesale Corp.',        sector: 'Consumer',      subIndustry: 'Consumer Staples Merchandise Retail',        hq: 'Issaquah, WA' },
  { ticker: 'AVGO',  name: 'Broadcom Inc.',                 sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'Palo Alto, CA' },
  { ticker: 'WMT',   name: 'Walmart Inc.',                  sector: 'Consumer',      subIndustry: 'Consumer Staples Merchandise Retail',        hq: 'Bentonville, AR' },
  { ticker: 'MCD',   name: "McDonald's Corporation",        sector: 'Consumer',      subIndustry: 'Restaurants',                                hq: 'Chicago, IL' },
  { ticker: 'CSCO',  name: 'Cisco Systems Inc.',            sector: 'Technology',    subIndustry: 'Communications Equipment',                   hq: 'San Jose, CA' },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific Inc.', sector: 'Healthcare',    subIndustry: 'Life Sciences Tools & Services',             hq: 'Waltham, MA' },
  { ticker: 'ACN',   name: 'Accenture plc',                 sector: 'Technology',    subIndustry: 'IT Consulting & Other Services',             hq: 'Dublin, Ireland' },
  { ticker: 'ABT',   name: 'Abbott Laboratories',           sector: 'Healthcare',    subIndustry: 'Health Care Equipment',                      hq: 'Abbott Park, IL' },
  { ticker: 'CRM',   name: 'Salesforce Inc.',               sector: 'Technology',    subIndustry: 'Application Software',                       hq: 'San Francisco, CA' },
  { ticker: 'DHR',   name: 'Danaher Corporation',           sector: 'Healthcare',    subIndustry: 'Health Care Equipment',                      hq: 'Washington, D.C.' },
  { ticker: 'NFLX',  name: 'Netflix Inc.',                  sector: 'Technology',    subIndustry: 'Movies & Entertainment',                     hq: 'Los Gatos, CA' },
  { ticker: 'AMD',   name: 'Advanced Micro Devices Inc.',   sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'Santa Clara, CA' },
  { ticker: 'INTC',  name: 'Intel Corporation',             sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'Santa Clara, CA' },
  { ticker: 'QCOM',  name: 'Qualcomm Inc.',                 sector: 'Technology',    subIndustry: 'Semiconductors',                             hq: 'San Diego, CA' },
  { ticker: 'TXN',   name: 'Texas Instruments Inc.',        sector: 'Technology',    subIndustry: 'Analog Semiconductors',                      hq: 'Dallas, TX' },
  { ticker: 'NEE',   name: 'NextEra Energy Inc.',           sector: 'Energy',        subIndustry: 'Electric Utilities',                         hq: 'Juno Beach, FL' },
  { ticker: 'UNP',   name: 'Union Pacific Corporation',     sector: 'Industrial',    subIndustry: 'Railroads',                                  hq: 'Omaha, NE' },
  { ticker: 'LOW',   name: "Lowe's Companies Inc.",         sector: 'Consumer',      subIndustry: 'Home Improvement Retail',                    hq: 'Mooresville, NC' },
  { ticker: 'BA',    name: 'The Boeing Company',            sector: 'Industrial',    subIndustry: 'Aerospace & Defense',                        hq: 'Arlington, VA' },
  { ticker: 'GS',    name: 'The Goldman Sachs Group Inc.',  sector: 'Finance',       subIndustry: 'Investment Banking & Brokerage',             hq: 'New York, NY' },
  { ticker: 'MS',    name: 'Morgan Stanley',                sector: 'Finance',       subIndustry: 'Investment Banking & Brokerage',             hq: 'New York, NY' },
  { ticker: 'AXP',   name: 'American Express Company',      sector: 'Finance',       subIndustry: 'Consumer Finance',                           hq: 'New York, NY' },
  { ticker: 'BLK',   name: 'BlackRock Inc.',                sector: 'Finance',       subIndustry: 'Asset Management & Custody Banks',           hq: 'New York, NY' },
  { ticker: 'CAT',   name: 'Caterpillar Inc.',              sector: 'Industrial',    subIndustry: 'Construction Machinery & Heavy Equipment',   hq: 'Irving, TX' },
  { ticker: 'DE',    name: 'Deere & Company',               sector: 'Industrial',    subIndustry: 'Agricultural & Farm Machinery',              hq: 'Moline, IL' },
  { ticker: 'GE',    name: 'GE Aerospace',                  sector: 'Industrial',    subIndustry: 'Aerospace & Defense',                        hq: 'Evendale, OH' },
  { ticker: 'RTX',   name: 'RTX Corporation',               sector: 'Industrial',    subIndustry: 'Aerospace & Defense',                        hq: 'Arlington, VA' },
  { ticker: 'LMT',   name: 'Lockheed Martin Corporation',   sector: 'Industrial',    subIndustry: 'Aerospace & Defense',                        hq: 'Bethesda, MD' },

  // ── Airlines ──
  { ticker: 'DAL',   name: 'Delta Air Lines Inc.',           sector: 'Airlines',      subIndustry: 'Passenger Airlines',                         hq: 'Atlanta, GA' },
  { ticker: 'UAL',   name: 'United Airlines Holdings Inc.',  sector: 'Airlines',      subIndustry: 'Passenger Airlines',                         hq: 'Chicago, IL' },
  { ticker: 'AAL',   name: 'American Airlines Group Inc.',   sector: 'Airlines',      subIndustry: 'Passenger Airlines',                         hq: 'Fort Worth, TX' },
  { ticker: 'LUV',   name: 'Southwest Airlines Co.',         sector: 'Airlines',      subIndustry: 'Low-Cost Airlines',                          hq: 'Dallas, TX' },
  { ticker: 'ALK',   name: 'Alaska Air Group Inc.',          sector: 'Airlines',      subIndustry: 'Passenger Airlines',                         hq: 'Seattle, WA' },
  { ticker: 'JBLU',  name: 'JetBlue Airways Corporation',    sector: 'Airlines',      subIndustry: 'Low-Cost Airlines',                          hq: 'Long Island City, NY' },
  { ticker: 'SAVE',  name: 'Spirit Airlines Inc.',           sector: 'Airlines',      subIndustry: 'Ultra Low-Cost Airlines',                    hq: 'Dania Beach, FL' },
  { ticker: 'HA',    name: 'Hawaiian Holdings Inc.',         sector: 'Airlines',      subIndustry: 'Passenger Airlines',                         hq: 'Honolulu, HI' },
  { ticker: 'RYAAY', name: 'Ryanair Holdings plc',           sector: 'Airlines',      subIndustry: 'Low-Cost Airlines (Europe)',                  hq: 'Dublin, Ireland' },
  { ticker: 'SKYW',  name: 'SkyWest Inc.',                   sector: 'Airlines',      subIndustry: 'Regional Airlines',                          hq: 'St. George, UT' },
  { ticker: 'MESA',  name: 'Mesa Air Group Inc.',            sector: 'Airlines',      subIndustry: 'Regional Airlines',                          hq: 'Phoenix, AZ' },
  { ticker: 'ALGT',  name: 'Allegiant Travel Company',       sector: 'Airlines',      subIndustry: 'Leisure Airlines',                           hq: 'Las Vegas, NV' },

  // ── Oil & Gas — Integrated Majors ──
  { ticker: 'SHEL',  name: 'Shell plc',                      sector: 'Oil & Gas',     subIndustry: 'Integrated Oil & Gas',                       hq: 'London, UK' },
  { ticker: 'BP',    name: 'BP plc',                         sector: 'Oil & Gas',     subIndustry: 'Integrated Oil & Gas',                       hq: 'London, UK' },
  { ticker: 'TTE',   name: 'TotalEnergies SE',               sector: 'Oil & Gas',     subIndustry: 'Integrated Oil & Gas',                       hq: 'Courbevoie, France' },
  { ticker: 'COP',   name: 'ConocoPhillips',                 sector: 'Oil & Gas',     subIndustry: 'Exploration & Production',                   hq: 'Houston, TX' },
  { ticker: 'EOG',   name: 'EOG Resources Inc.',             sector: 'Oil & Gas',     subIndustry: 'Exploration & Production',                   hq: 'Houston, TX' },
  { ticker: 'PXD',   name: 'Pioneer Natural Resources Co.',  sector: 'Oil & Gas',     subIndustry: 'Exploration & Production',                   hq: 'Irving, TX' },
  { ticker: 'OXY',   name: 'Occidental Petroleum Corp.',     sector: 'Oil & Gas',     subIndustry: 'Exploration & Production',                   hq: 'Houston, TX' },
  { ticker: 'DVN',   name: 'Devon Energy Corporation',       sector: 'Oil & Gas',     subIndustry: 'Exploration & Production',                   hq: 'Oklahoma City, OK' },
  { ticker: 'HES',   name: 'Hess Corporation',               sector: 'Oil & Gas',     subIndustry: 'Exploration & Production',                   hq: 'New York, NY' },
  { ticker: 'MPC',   name: 'Marathon Petroleum Corp.',        sector: 'Oil & Gas',     subIndustry: 'Oil Refining & Marketing',                   hq: 'Findlay, OH' },
  { ticker: 'VLO',   name: 'Valero Energy Corporation',      sector: 'Oil & Gas',     subIndustry: 'Oil Refining & Marketing',                   hq: 'San Antonio, TX' },
  { ticker: 'PSX',   name: 'Phillips 66',                    sector: 'Oil & Gas',     subIndustry: 'Oil Refining & Marketing',                   hq: 'Houston, TX' },

  // ── Oil & Gas — Services & Equipment ──
  { ticker: 'SLB',   name: 'Schlumberger Limited',           sector: 'Oil & Gas',     subIndustry: 'Oilfield Services',                          hq: 'Houston, TX' },
  { ticker: 'HAL',   name: 'Halliburton Company',            sector: 'Oil & Gas',     subIndustry: 'Oilfield Services',                          hq: 'Houston, TX' },
  { ticker: 'BKR',   name: 'Baker Hughes Company',           sector: 'Oil & Gas',     subIndustry: 'Oilfield Equipment & Services',              hq: 'Houston, TX' },

  // ── Oil & Gas — Pipelines & Midstream ──
  { ticker: 'WMB',   name: 'Williams Companies Inc.',        sector: 'Oil & Gas',     subIndustry: 'Oil & Gas Pipelines',                        hq: 'Tulsa, OK' },
  { ticker: 'KMI',   name: 'Kinder Morgan Inc.',             sector: 'Oil & Gas',     subIndustry: 'Oil & Gas Pipelines',                        hq: 'Houston, TX' },
  { ticker: 'OKE',   name: 'ONEOK Inc.',                     sector: 'Oil & Gas',     subIndustry: 'Oil & Gas Pipelines',                        hq: 'Tulsa, OK' },
  { ticker: 'ET',    name: 'Energy Transfer LP',             sector: 'Oil & Gas',     subIndustry: 'Oil & Gas Pipelines',                        hq: 'Dallas, TX' },

  // ── Oil & Gas — LNG & Natural Gas ──
  { ticker: 'LNG',   name: 'Cheniere Energy Inc.',           sector: 'Oil & Gas',     subIndustry: 'LNG Export',                                 hq: 'Houston, TX' },
  { ticker: 'EQT',   name: 'EQT Corporation',                sector: 'Oil & Gas',     subIndustry: 'Natural Gas Exploration & Production',       hq: 'Pittsburgh, PA' },
  { ticker: 'AR',    name: 'Antero Resources Corp.',         sector: 'Oil & Gas',     subIndustry: 'Natural Gas Exploration & Production',       hq: 'Denver, CO' },
  { ticker: 'RRC',   name: 'Range Resources Corp.',          sector: 'Oil & Gas',     subIndustry: 'Natural Gas Exploration & Production',       hq: 'Fort Worth, TX' },
];

// Sector groupings for filter UI
export const sectorGroups = {
  'All':        null,
  'Tech':       'Technology',
  'Finance':    'Finance',
  'Healthcare': 'Healthcare',
  'Oil & Gas':  'Oil & Gas',
  'Airlines':   'Airlines',
  'Energy':     'Energy',
  'Consumer':   'Consumer',
  'Industrial': 'Industrial',
};
